spring:
  datasource:
    url: jdbc:mysql://133.186.241.167:3306/project_be7_nuribooks_dev?useSSL=false&serverTimezone=UTC
    username: be7_nuribooks
    password: '@f3hgB7jc@KvWJQZ'
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource

  datasource-meta:
    url: jdbc:mysql://133.186.241.167:3306/nhn_academy_101
    username: nhn_academy_101
    password: mH9oewcq!
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize-schema: always  # 배치 메타데이터 테이블 자동 생성

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: debug
